<template>
    <section class="section has-background-white">
        <div class="container">
            <div class="content">
                <h1>Site Notice</h1>
                <h2>Information provided according to Sec. 5 German Telemedia Act (TMG):</h2>
                <p>kreait GmbH<br />
                Oberescher Weg 7 <br />
                53501 Grafschaft</p>
                <h2>Represented by:</h2>
                <p> kreait GmbH, vertreten durch Gowrynath Sivaganeshamoorthy und Markus Giordano</p>
                <h2>Contact:</h2>
                <p>Telephone: +49 2641 8939580<br />
                Telefax: +49 2641 8939589<br />
                Email: info@kreait.com</p>
                <h2>Register entry:</h2>
                <p>Entry in the Handelsregister. <br />
                Registering court:Koblenz <br />
                Registration number: HRB22989</p>
                <h2>VAT:</h2>
                <p>VAT Id number according to Sec. 27 a German Value Added Tax Act:<br />
                DE281555713</p>
                <h2>Dispute resolution</h2>
                <p>We do not take part in online dispute resolutions at consumer arbitration boards.</p>
                <h3>Liability for Contents</h3> <p>As service providers, we are liable for own contents of these websites according to Sec. 7, paragraph 1 German Telemedia Act (TMG). However, according to Sec. 8 to 10 German Telemedia Act (TMG), service providers are not obligated to permanently monitor submitted or stored information or to search for evidences that indicate illegal activities.</p> <p>Legal obligations to removing information or to blocking the use of information remain unchallenged. In this case, liability is only possible at the time of knowledge about a specific violation of law. Illegal contents will be removed immediately at the time we get knowledge of them.</p> <h3>Liability for Links</h3> <p>Our offer includes links to external third party websites. We have no influence on the contents of those websites, therefore we cannot guarantee for those contents. Providers or administrators of linked websites are always responsible for their own contents.</p> <p>The linked websites had been checked for possible violations of law at the time of the establishment of the link. Illegal contents were not detected at the time of the linking. A permanent monitoring of the contents of linked websites cannot be imposed without reasonable indications that there has been a violation of law. Illegal links will be removed immediately at the time we get knowledge of them.</p> <h3>Copyright</h3> <p>Contents and compilations published on these websites by the providers are subject to German copyright laws. Reproduction, editing, distribution as well as the use of any kind outside the scope of the copyright law require a written permission of the author or originator. Downloads and copies of these websites are permitted for private use only.<br /> The commercial use of our contents without permission of the originator is prohibited.</p> <p>Copyright laws of third parties are respected as long as the contents on these websites do not originate from the provider. Contributions of third parties on this site are indicated as such. However, if you notice any violations of copyright law, please inform us. Such contents will be removed immediately.</p>
                <h1>Privacy Policy</h1>
                <h2>1. An overview of data protection</h2>
                <h3>General information</h3> <p>The following information will provide you with an easy to navigate overview of what will happen with your personal data when you visit our website. The term â€œpersonal data comprises all data that can be used to personally identify you. For detailed information about the subject matter of data protection, please consult our Data Protection Declaration, which we have included beneath this copy.</p>
                <h3>Data recording on our website</h3> <p><strong>Who is the responsible party for the recording of data on this website (i.e. the controller)?</strong></p> <p>The data on this website is processed by the operator of the website, whose contact information is available under section â€œInformation Required by Law on this website.</p> <p><strong>How do we record your data?</strong></p> <p>We collect your data as a result of your sharing of your data with us. This may, for instance be information you enter into our contact form.</p> <p>Our IT systems automatically record other data when you visit our website. This data comprises primarily technical information (e.g. web browser, operating system or time the site was accessed). This information is recorded automatically when you access our website.</p> <p><strong>What are the purposes we use your data for?</strong></p> <p>A portion of the information is generated to guarantee the error free provision of the website. Other data may be used to analyse your user patterns.</p> <p><strong>What rights do you have as far as your information is concerned?</strong></p> <p>You have the right to receive information about the source, recipients and purposes of your archived personal data at any time without having to pay a fee for such disclosures. You also have the right to demand that your data are rectified, blocked or eradicated. Please do not hesitate to contact us at any time under the address disclosed in section â€œInformation Required by Law on this website if you have questions about this or any other data protection related issues. You also have the right to log a complaint with the competent supervising agency.</p> <p>Moreover, under certain circumstances, you have the right to demand the restriction of the processing of your personal data. For details, please consult the Data Protection Declaration under section â€œRight to Restriction of Data Processing.</p>
                <h3>Analysis tools and tools provided by third parties</h3> <p>There is a possibility that your browsing patterns will be statistically analysed when your visit our website. Such analyses are performed primarily with cookies and with what we refer to as analysis programmes. As a rule, the analyses of your browsing patterns are conducted anonymously; i.e. the browsing patterns cannot be traced back to you. You have the option to object to such analyses or you can prevent their performance by not using certain tools. For detailed information about this, please consult our Data Protection Declaration below.</p> <p>You do have the option to object to such analyses. We will brief you on the objection options in this Data Protection Declaration.</p>
                <h2>2. General information and mandatory information</h2>
                <h3>Data protection</h3> <p>The operators of this website and its pages take the protection of your personal data very seriously. Hence, we handle your personal data as confidential information and in compliance with the statutory data protection regulations and this Data Protection Declaration.</p> <p>Whenever you use this website, a variety of personal information will be collected. Personal data comprises data that can be used to personally identify you. This Data Protection Declaration explains which data we collect as well as the purposes we use this data for. It also explains how, and for which purpose the information is collected.</p> <p>We herewith advise you that the transmission of data via the Internet (i.e. through e-mail communications) may be prone to security gaps. It is not possible to completely protect data against third party access.</p>
                <h3>Information about the responsible party (referred to as the controller in the GDPR)</h3> <p>The data processing controller on this website is:</p> <p>kreait GmbH <br />
                Oberescher Weg 7 <br />
                53501 Grafschaft</p>
                <p>Phone: +49 2641 8939580<br />
                E-mail: info@kreait.com</p>
                <p>The controller is the natural person or legal entity that single-handedly or jointly with others makes decisions as to the purposes of and resources for the processing of personal data (e.g. names, e-mail addresses, etc.).</p>
                <h3>Revocation of your consent to the processing of data</h3> <p>A wide range of data processing transactions are possible only subject to your express consent. You can also revoke at any time any consent you have already given us. To do so, all you are required to do is sent us an informal notification via e-mail. This shall be without prejudice to the lawfulness of any data collection that occurred prior to your revocation.</p>
                <h3>Right to object to the collection of data in special cases; right to object to direct advertising (Art. 21 GDPR)</h3> <p><strong>In the event that data are processed on the basis of Art. 6 Sect. 1 lit. e or f GDPR, you have the right to at any time object to the processing of your personal data based on grounds arising from your unique situation. This also applies to any profiling based on these provisions. To determine the legal basis, on which any processing of data is based, please consult this Data Protection Declaration. If you log an objection, we will no longer process your affected personal data, unless we are in a position to present compelling protection worthy grounds for the processing of your data, that outweigh your interests, rights and freedoms or if the purpose of the processing is the claiming, exercising or defence of legal entitlements (objection pursuant to Art. 21 Sect. 1 GDPR).</strong></p> <p><strong>If your personal data is being processed in order to engage in direct advertising, you have the right to at any time object to the processing of your affected personal data for the purposes of such advertising. This also applies to profiling to the extent that it is affiliated with such direct advertising. If you object, your personal data will subsequently no longer be used for direct advertising purposes (objection pursuant to Art. 21 Sect. 2 GDPR).</strong></p>
                <h3>Right to log a complaint with the competent supervisory agency</h3> <p>In the event of violations of the GDPR, data subjects are entitled to log a complaint with a supervisory agency, in particular in the member state where they usually maintain their domicile, place of work or at the place where the alleged violation occurred. The right to log a complaint is in effect regardless of any other administrative or court proceedings available as legal recourses.</p>
                <h3>Right to data portability</h3> <p>You have the right to demand that we hand over any data we automatically process on the basis of your consent or in order to fulfil a contract be handed over to you or a third party in a commonly used, machine readable format. If you should demand the direct transfer of the data to another controller, this will be done only if it is technically feasible.</p>
                <h3>SSL and/or TLS encryption</h3> <p>For security reasons and to protect the transmission of confidential content, such as purchase orders or inquiries you submit to us as the website operator, this website uses either an SSL or a TLS encryption programme. You can recognise an encrypted connection by checking whether the address line of the browser switches from http:// to https:// and also by the appearance of the lock icon in the browser line.</p> <p>If the SSL or TLS encryption is activated, data you transmit to us cannot be read by third parties.</p>
                <h3>Information about, blockage, rectification and eradication of data</h3> <p>Within the scope of the applicable statutory provisions, you have the right to at any time demand information about your archived personal data, their source and recipients as well as the purpose of the processing of your data. You may also have a right to have your data rectified, blocked or eradicated. If you have questions about this subject matter or any other questions about personal data, please do not hesitate to contact us at any time at the address provided in section â€œInformation Required by Law.</p>
                <h3>Right to demand processing restrictions</h3> <p>You have the right to demand the imposition of restrictions as far as the processing of your personal data is concerned. To do so, you may contact us at any time at the address provided in section â€œInformation Required by Law. The right to demand restriction of processing applies in the following cases:</p> <ul> <li>In the event that you should dispute the correctness of your data archived by us, we will usually need some time to verify this claim. During the time that this investigation is ongoing, you have the right to demand that we restrict the processing of your personal data.</li> <li>If the processing of your personal data was/is conducted in an unlawful manner, you have the option to demand the restriction of the processing of your data in lieu of demanding the eradication of this data.</li> <li>If we do not need your personal data any longer and you need it to exercise, defend or claim legal entitlements, you have the right to demand the restriction of the processing of your personal data instead of its eradication.</li> <li>If you have raised an objection pursuant to Art. 21 Sect. 1 GDPR, your rights and our rights will have to be weighed against each other. As long as it has not been determined whose interests prevail, you have the right to demand a restriction of the processing of your personal data.</li> </ul> <p>If you have restricted the processing of your personal data, these data â€“ with the exception of their archiving â€“ may be processed only subject to your consent or to claim, exercise or defend legal entitlements or to protect the rights of other natural persons or legal entities or for important public interest reasons cited by the European Union or a member state of the EU.</p>
                <h2>3. Data protection officer</h2>
                <h3>Designation of a data protection officer as mandated by law</h3> <p>We have appointed a data protection officer for our company.</p>
                <p>Lennart Zellmer<br />
                kreait GmbH<br />
                Reinhardtstrasse 7 <br />
                10117 Berlin</p>
                <p>Phone: +49 2641 8939580<br />
                E-mail: datenschutz@kreait.com</p>
                <h2>4. Recording of data on our website</h2>
                <h3>Cookies</h3> <p>In some instances, our website and its pages use so-called cookies. Cookies do not cause any damage to your computer and do not contain viruses. The purpose of cookies is to make our website more user friendly, effective and more secure. Cookies are small text files that are placed on your computer and stored by your browser.</p> <p>Most of the cookies we use are so-called â€œsession cookies. They are automatically deleted after your leave our site. Other cookies will remain archived on your device until you delete them. These cookies enable us to recognise your browser the next time you visit our website.</p> <p>You can adjust the settings of your browser to make sure that you are notified every time cookies are placed and to enable you to accept cookies only in specific cases or to exclude the acceptance of cookies for specific situations or in general and to activate the automatic deletion of cookies when you close your browser. If you deactivate cookies, the functions of this website may be limited.</p> <p>Cookies that are required for the performance of the electronic communications transaction or to provide certain functions you want to use (e.g. the shopping cart function), are stored on the basis of Art. 6 Sect. 1 lit. f GDPR. The website operator has a legitimate interest in storing cookies to ensure the technically error free and optimised provision of the operator's services. If other cookies (e.g. cookies for the analysis of your browsing patterns) should be stored, they are addressed separately in this Data Protection Declaration.</p>
                <h3>Server log files</h3> <p>The provider of this website and its pages automatically collects and stores information in so-called server log files, which your browser communicates to us automatically. The information comprises:</p> <ul> <li>The type and version of browser used</li> <li>The used operating system</li> <li>Referrer URL</li> <li>The hostname of the accessing computer</li> <li>The time of the server inquiry</li> <li>The IP address</li> </ul> <p>This data is not merged with other data sources.</p> <p>This data is recorded on the basis of Art. 6 Sect. 1 lit. f GDPR. The operator of the website has a legitimate interest in the technically error free depiction and the optimization of the operator's website. In order to achieve this, server log files must be recorded.</p>
                <h3>Contact form</h3> <p>If you submit inquiries to us via our contact form, the information provided in the contact form as well as any contact information provided therein will be stored by us in order to handle your inquiry and in the event that we have further questions. We will not share this information without your consent.</p> <p>Hence, the processing of the data entered into the contact form occurs exclusively based on your consent (Art. 6 Sect. 1 lit. a GDPR). You have the right to revoke at any time any consent you have already given us. To do so, all you are required to do is sent us an informal notification via e-mail. This shall be without prejudice to the lawfulness of any data collection that occurred prior to your revocation.</p> <p>The information you have entered into the contact form shall remain with us until you ask us to eradicate the data, revoke your consent to the archiving of data or if the purpose for which the information is being archived no longer exists (e.g. after we have concluded our response to your inquiry). This shall be without prejudice to any mandatory legal provisions â€“ in particular retention periods.</p>
                <h3>Request by e-mail, telephone or fax</h3> <p>If you contact us by e-mail, telephone or fax, your request, including all resulting personal data (name, request) will be stored and processed by us for the purpose of processing your request. We do not pass these data on without your consent.</p> <p>The processing of these data is based on Art. 6 para. 1 lit. b GDPR, if your request is related to the execution of a contract or if it is necessary to carry out pre-contractual measures. In all other cases, the processing is based on your consent (Article 6 (1) a GDPR) and/or on our legitimate interests (Article 6 (1) (f) GDPR), since we have a legitimate interest in the effective processing of requests addressed to us.</p> <p>The data sent by you to us via contact requests remain with us until you request us to delete, revoke your consent to the storage or the purpose for the data storage lapses (e.g. after completion of your request). Mandatory statutory provisions - in particular statutory retention periods - remain unaffected.</p>
                <h2>5. Analysis tools and advertising</h2>
                <h3>Google Analytics</h3> <p>This website uses functions of the web analysis service Google Analytics. The provider of this service is Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p> <p>Google Analytics uses so-called cookies. Cookies are text files, which are stored on your computer and that enable an analysis of the use of the website by users. The information generated by cookies on your use of this website is usually transferred to a Google server in the United States, where it is stored.</p> <p>The storage of Google Analytics cookies and the utilization of this analysis tool are based on Art. 6 Sect. 1 lit. f GDPR. The operator of this website has a legitimate interest in the analysis of user patterns to optimize both, the services offered online and the operator's advertising activities.</p> <p><strong>IP anonymization</strong></p> <p>On this website, we have activated the IP anonymization function. As a result, your IP address will be abbreviated by Google within the member states of the European Union or in other states that have ratified the Convention on the European Economic Area prior to its transmission to the United States. The full IP address will be transmitted to one of Google's servers in the United States and abbreviated there only in exceptional cases. On behalf of the operator of this website, Google shall use this information to analyse your use of this website to generate reports on website activities and to render other services to the operator of this website that are related to the use of the website and the Internet. The IP address transmitted in conjunction with Google Analytics from your browser shall not be merged with other data in Google's possession.</p>
                <p><strong>Browser plug-in</strong></p> <p>You do have the option to prevent the archiving of cookies by making pertinent changes to the settings of your browser software. However, we have to point out that in this case you may not be able to use all of the functions of this website to their fullest extent. Moreover, you have the option prevent the recording of the data generated by the cookie and affiliated with your use of the website (including your IP address) by Google as well as the processing of this data by Google by downloading and installing the browser plug-in available under the following link: <a href="https://tools.google.com/dlpage/gaoptout?hl=en" target="_blank" rel="noopener">https://tools.google.com/dlpage/gaoptout?hl=en</a>.</p> <p><strong>Objection to the recording of data</strong></p> <p>You have the option to prevent the recording of your data by Google Analytics by clicking on the following link. This will result in the placement of an opt out cookie, which prevents the recording of your data during future visits to this website: <a href="javascript:gaOptout();">Google Analytics deactivation</a>.</p> <p>For more information about the handling of user data by Google Analytics, please consult Google's Data Privacy Declaration at: <a href="https://support.google.com/analytics/answer/6004245?hl=de" target="_blank" rel="noopener">https://support.google.com/analytics/answer/6004245?hl=en</a>.</p><p><strong>Contract data processing</strong></p> <p>We have executed a contract data processing agreement with Google and are implementing the stringent provisions of the German data protection agencies to the fullest when using Google Analytics.</p>
                <h3>Hotjar</h3>
                <p>We use <a href="https://www.hotjar.com/" target="_blank">Hotjar</a> in order to better understand our users’ needs and to optimize this service and experience. Hotjar is a technology service that helps us better understand our users experience (e.g. how much time they spend on which pages, which links they choose to click, what users do and don’t like, etc.) and this enables us to build and maintain our service with user feedback. Hotjar uses cookies and other technologies to collect data on our users’ behavior and their devices (in particular device's IP address (captured and stored only in anonymized form), device screen size, device type (unique device identifiers), browser information, geographic location (country only), preferred language used to display our website). Hotjar stores this information in a pseudonymized user profile. Neither Hotjar nor we will ever use this information to identify individual users or to match it with further data on an individual user. For further details, please see Hotjar’s privacy policy by clicking on <a href="https://www.hotjar.com/legal/policies/privacy" target="_blank">this link</a>.</p>
                <p>You can opt-out to the creation of a user profile, Hotjar’s storing of data about your usage of our site and Hotjar’s use of tracking cookies on other websites by following <a href="https://www.hotjar.com/legal/compliance/opt-out" target="_blank">this opt-out link</a>.</p>
                <!--
                <h2>6. Plug-ins and Tools</h2>
                <h3>YouTube</h3> <p>Our website uses plug-ins of the YouTube platform, which is operated by Google. The website operator is YouTube, LLC, 901 Cherry Ave., San Bruno, CA 94066, USA.</p> <p>If you visit a page on our website into which a YouTube plug-in has been integrated, a connection with YouTube's servers will be established. As a result, the YouTube server will be notified, which of our pages you have visited.</p> <p>Furthermore, YouTube will be able to place various cookies on your device. With the assistance of these cookies, YouTube will be able to obtain information about our website visitor. Among other things, this information will be used to generate video statistics with the aim of improving the user friendliness of the site and to prevent attempts to commit fraud. These cookies will stay on your device until you delete them.</p> <p>If you are logged into your YouTube account while you visit our site, you enable YouTube to directly allocate your browsing patterns to your personal profile. You have the option to prevent this by logging out of your YouTube account.</p> <p>The use of YouTube is based on our interest in presenting our online content in an appealing manner. Pursuant to Art. 6 Sect. 1 lit. f GDPR, this is a legitimate interest.</p> <p>For more information on how YouTube handles user data, please consult the YouTube Data Privacy Policy under: <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noopener">https://policies.google.com/privacy?hl=en</a>.</p>
                <h3>Vimeo</h3> <p>Our website uses plug-ins of the video portal Vimeo. The provider is Vimeo Inc., 555 West 18th Street, New York, New York 10011, USA.</p> <p>If you visit one of the pages on our website into which a Vimeo plug-in has been integrated, a connection to Vimeo's servers will be established. As a consequence, the Vimeo server will receive information as to which of our pages you have visited. Moreover, Vimeo will receive your IP address. This will also happen if you are not logged into Vimeo or do not have an account with Vimeo. The information recorded by Vimeo will be transmitted to Vimeo's server in the United States.</p> <p>If you are logged into your Vimeo account, you enable Vimeo to directly allocate your browsing patterns to your personal profile. You can prevent this by logging out of your Vimeo account.</p> <p>The use of Vimeo is based on our interest in presenting our online content in an appealing manner. Pursuant to Art. 6 Sect. 1 lit. f GDPR, this is a legitimate interest.</p> <p>For more information on how Vimeo handles user data, please consult the Vimeo Data Privacy Policy under: <a href="https://vimeo.com/privacy" target="_blank" rel="noopener">https://vimeo.com/privacy</a>.</p>
                <h3>Google Web Fonts</h3> <p>To ensure that fonts used on this website are uniform, this website uses so-called Web Fonts provided by Google. When you access a page on our website, your browser will load the required web fonts into your browser cache to correctly display text and fonts.</p> <p>To do this, the browser you use will have to establish a connection with Google's servers. As a result, Google will learn that your IP address was used to access our website. The use of Google Web Fonts is based on our interest in presenting our online content in a uniform and appealing way. According to Art. 6 Sect. 1 lit. f GDPR, this is a legitimate interest.</p> <p>If your browser should not support Web Fonts, a standard font installed on your computer will be used.</p> <p>For more information on Google Web Fonts, please follow this link: <a href="https://developers.google.com/fonts/faq" target="_blank" rel="noopener">https://developers.google.com/fonts/faq</a> and consult Google's Data Privacy Declaration under: <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noopener">https://policies.google.com/privacy?hl=en</a>.</p>
                <h3>Google Maps</h3> <p>Via an API, this website uses the mapping service Google Maps. The provider is Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p> <p>To enable the use of the Google Maps features, your IP address must be stored. As a rule, this information is transferred to one of Google's servers in the United States, where it is archived. The operator of this website has no control over the data transfer.</p> <p>We use Google Maps to present our online content in an appealing manner and to make the locations disclosed on our website easy to find. This constitutes a legitimate interest as defined in Art. 6 Sect. 1 lit. f GDPR.</p> <p>For more information on the handling of user data, please review Google's Data Privacy Declaration under: <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noopener">https://policies.google.com/privacy?hl=en</a>.</p>
                <h3>SoundCloud</h3> <p>We may have integrated plug-ins of the social network SoundCloud (SoundCloud Limited, Berners House, 47-48 Berners Street, London W1T 3NF, Great Britain) into our websites. You will be able to recognise such SoundCloud plug-ins by checking for the SoundCloud logo on the respective pages.</p> <p>Whenever you visit one of our websites, a direct connection between your browser and the SoundCloud server will be established immediately after the plug-in has been activated. As a result, SoundCloud will be notified that you have used your IP address to visit our site. If you click the Like button or the Share button while you are logged into your Sound Cloud user account, you can link the content of our websites to your SoundCloud profile and/or share the content. Consequently, SoundCloud will be able to allocate the visit to our website to your user account. We emphasize that we as the provider of the websites do not have any knowledge of the data transferred and the use of this data by SoundCloud.</p> <p>We use SoundCloud on the basis of Art. 6 Sect. 1 lit. f GDPR. The website operator has a legitimate interest in attaining the highest level of visibility on social media.</p> <p>For more information about this, please consult SoundCloud's Data Privacy Declaration at: <a href="https://soundcloud.com/pages/privacy" target="_blank" rel="noopener">https://soundcloud.com/pages/privacy</a>.</p> <p>If you prefer not to have your visit to our websites allocated to your SoundCloud user account by SoundCloud, please log out of your SoundCloud user account before you activate content of the SoundCloud plug-in.</p>
                <h3>Spotify</h3> <p>We have integrated features of the Spotify music platform into our websites. The provider is Spotify AB, Birger Jarlsgatan 61, 113 56 Stockholm, Sweden. You will be able to recognise Spotify plug-ins when you see the green logo on our pages. An overview of Spotify's plug-ins can be found at: <a href="https://developer.spotify.com" target="_blank" rel="noopener">https://developer.spotify.com</a>.</p> <p>The plug-in makes it possible to establish a direct connection between your browser and Spotify's server when you visit our websites. As a result, Spotify receives the information that you visited our site with your IP address. If you click the Spotify button while you are logged into your Spotify account, you have the option to link content from our page with your Spotify profile. Consequently, Spotify will be in a position to allocate your visit to our websites to your user account.</p> <p>The data processing activities are based on Art. 6 Sect. 1 lit. f GDPR. Accordingly, the website operator has a legitimate interest in placing respective acoustic content on the operator's website.</p> <p>For more information, please consult Spotify's Data Protection Declaration under: <a href="https://www.spotify.com/us/legal/privacy-policy/" target="_blank" rel="noopener">https://www.spotify.com/us/legal/privacy-policy/</a>.</p> <p>If you do not want Spotify to be able to allocate the visit of our websites to your Spotify user account, please log out of your Spotify user account while visiting our sites.</p>
                -->
            </div>
        </div>
    </section>
</template>

<script>
export default {
  name: "SectionImprint"
};
</script>

<style lang="scss" scoped>
</style>
